version: '3'
services:
  backend:
    container_name: backend
    restart: unless-stopped
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - check_box_network

  db:
    image: postgres:15
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_PASSWORD}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - check_box_network

  test_db:
    image: postgres:15
    container_name: test_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: test_postgres
      POSTGRES_PASSWORD: test_postgres
      POSTGRES_DB: test_postgres
    expose:
      - 5433
    volumes:
      - postgres_data:/var/lib/postgresql/test_data
    networks:
      - check_box_network

volumes:
  postgres_data:

networks:
  check_box_network:
    driver: bridge
