"""add_unique_check_into_payment

Revision ID: 4e97fb3419b8
Revises: bd5e47b17eab
Create Date: 2024-09-22 21:43:12.346303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e97fb3419b8'
down_revision: Union[str, None] = 'bd5e47b17eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('receipt_link', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'payments', ['receipt_link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'receipt_link')
    # ### end Alembic commands ###
