"""add_total_payment_model

Revision ID: 5eb6f5ba1e23
Revises: fd3aefd2b376
Create Date: 2024-09-21 21:52:57.217140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb6f5ba1e23'
down_revision: Union[str, None] = 'fd3aefd2b376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'total')
    # ### end Alembic commands ###
