"""add_fop_title_to_user

Revision ID: d9d785c000f4
Revises: 4e97fb3419b8
Create Date: 2024-09-23 11:29:03.257725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d785c000f4'
down_revision: Union[str, None] = '4e97fb3419b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fop_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fop_title')
    # ### end Alembic commands ###
